from __future__ import annotations


CANARY = """# HARBOR_CANARY: tests generated by FACET-Terminal"""
PYTEST_VERSION = "pytest==8.4.1"
CTRF_VERSION = "pytest-json-ctrf==0.3.5"
UV_VERSION = "0.9.7"


def build_test_sh(extra_packages: list[str] | None = None) -> str:
    """Build the Harbor-compatible pytest runner used by FACET-Terminal."""
    pkg_flags = ""
    for package in extra_packages or []:
        package = str(package).strip()
        if package:
            pkg_flags += f"  --with {package} \\\n"
    return f"""#!/bin/bash
set +e
mkdir -p /logs/verifier

if ! command -v curl >/dev/null 2>&1; then
  apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*
elif ! dpkg -s ca-certificates >/dev/null 2>&1; then
  apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
fi

if [ -f "$HOME/.local/bin/env" ]; then
  source "$HOME/.local/bin/env"
fi

if ! command -v uvx >/dev/null 2>&1; then
  curl -LsSf https://astral.sh/uv/{UV_VERSION}/install.sh | sh
  source "$HOME/.local/bin/env"
fi

uvx \\
  --with {PYTEST_VERSION} \\
{pkg_flags}  --with {CTRF_VERSION} \\
  pytest --ctrf /logs/verifier/ctrf.json /tests/test_state.py -rA

status=$?
if [ "$status" -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
exit 0
"""


def fallback_test_state(root: str) -> str:
    return f"""{CANARY}
from pathlib import Path


ROOT = Path({root!r})


def test_required_workspace_exists():
    assert ROOT.exists(), f"Task root {{ROOT}} does not exist"


def test_agent_created_nonempty_output():
    output_dir = ROOT / "output"
    assert output_dir.exists(), "Expected output directory does not exist"
    files = [path for path in output_dir.rglob("*") if path.is_file() and path.name != ".gitkeep"]
    assert files, "No non-placeholder output files were created"
    assert any(path.stat().st_size > 0 for path in files), "Created output files are empty"
"""
