from __future__ import annotations

import argparse
from pathlib import PurePosixPath
from typing import Any

from common.context import RunContext, utc_now
from common.hashing import file_hash
from common.io import read_json, read_jsonl, write_json, write_jsonl, write_text
from common.model_pool import ModelClient

from facet_terminal.pipeline import ArtifactWriter, base_image, candidate_dir, record_event, safe_rel_path, stage_cfg, stage_log_dir, stage_report_dir, task_root, worker_count, write_stage_report
from facet_terminal.prompts import PROMPT_VERSION
from facet_terminal.prompts_joint import JOINT_USER_PROMPT, render_joint_prompt
from facet_terminal.scheduler import run_batched
from facet_terminal.stages.instruction.stage import _profile_for_unit, fallback_instruction, instruction_ref_text
from facet_terminal.stages.solution.stage import normalize_script
from facet_terminal.stages.tests.env_context import load_or_build_selected_fixture_summaries, load_real_env_file_summary, read_generated_dockerfile
from facet_terminal.stages.tests.test_runner_templates import CANARY, build_test_sh, fallback_test_state


STAGE = "joint"
JOINT_CANARY = "# HARBOR_CANARY: tests generated by FACET-Terminal experimental joint strategy"


def normalize_joint_test_state(source: str, root: str) -> str:
    text = str(source or "").replace("\r\n", "\n").strip()
    if not text:
        text = fallback_test_state(root).replace(CANARY, JOINT_CANARY).strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("python"):
            text = text[len("python") :].strip()
    if not text.startswith(JOINT_CANARY):
        lines = text.splitlines()
        if lines and lines[0].startswith("# HARBOR_CANARY:"):
            lines[0] = JOINT_CANARY
            text = "\n".join(lines)
        else:
            text = JOINT_CANARY + "\n" + text
    compile(text, "test_state.py", "exec")
    return text.rstrip() + "\n"


def normalize_joint_test_sh(source: str) -> str:
    text = str(source or "").replace("\r\n", "\n").strip()
    if not text:
        text = build_test_sh([])
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("bash"):
            text = text[len("bash") :].strip()
    if not text.startswith("#!"):
        text = "#!/bin/bash\n" + text
    lines = text.splitlines()
    if not any("reward.txt" in line for line in lines):
        text = build_test_sh([])
    return text.rstrip() + "\n"


def read_optional_json(task: Any, rel_path: str) -> dict[str, Any]:
    path = task / rel_path
    if not path.exists():
        return {}
    try:
        payload = read_json(path)
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def joint_context(ctx: RunContext, cfg: dict[str, Any], unit: dict[str, Any]) -> dict[str, Any]:
    task_id = str(unit["task_id"])
    task = candidate_dir(ctx, task_id)
    root = task_root(cfg)
    real_summary = load_real_env_file_summary(task)
    fixture_summaries = load_or_build_selected_fixture_summaries(task, cfg, real_summary, prefix="joint_")
    return {
        "task_id": task_id,
        "instruction_ref": instruction_ref_text(ctx, unit),
        "real_env_file_summary": {
            "summary_type": real_summary.get("summary_type"),
            "task_root": real_summary.get("task_root", root),
            "counts": real_summary.get("counts", {}),
            "task_file_paths": real_summary.get("task_file_paths", []),
            "task_directory_paths": real_summary.get("task_directory_paths", []),
            "task_files": real_summary.get("task_files", []),
            "task_directories": real_summary.get("task_directories", []),
        },
        "selected_fixture_summaries": fixture_summaries,
        "environment_metadata": {
            "visible_file_count": len(real_summary.get("task_files") or []),
            "visible_directory_count": len(real_summary.get("task_directories") or []),
            "maturity": real_summary.get("maturity", {}),
            "validation": real_summary.get("validation", {}),
            "env_signals": read_optional_json(task, "pipeline_artifacts/environment/env_signals.json"),
            "env_checks": read_optional_json(task, "pipeline_artifacts/environment/build_runtime/env_checks.json"),
        },
        "generated_dockerfile": read_generated_dockerfile(task),
        "test_sh_template": build_test_sh(["<EXTRA_PUBLIC_PYPI_PACKAGE_IF_NEEDED>"]),
        "constraints": {
            "task_root": root,
            "base_image": base_image(ctx, cfg),
            "prompt_version": PROMPT_VERSION,
            "stage": STAGE,
        },
    }


def payload_from_model(ctx: RunContext, cfg: dict[str, Any], model_client: ModelClient, unit: dict[str, Any], context: dict[str, Any]) -> tuple[dict[str, Any], str | None, str | None]:
    task_id = str(unit["task_id"])
    root = task_root(cfg)
    prompt = render_joint_prompt(JOINT_USER_PROMPT, context, task_root=root, base_image=base_image(ctx, cfg))
    log_dir = stage_log_dir(ctx, STAGE, task_id)
    write_json(log_dir / "input_context.json", context)
    write_text(log_dir / "prompt.txt", prompt)
    profile = _profile_for_unit([str(item) for item in cfg.get("model_profiles", [])], str(unit.get("pair_id", task_id)))
    payload, call_id = model_client.chat_json("facet_terminal_joint", str(unit.get("pair_id", task_id)), "", prompt, profile)
    write_json(log_dir / "model_payload.json", payload)
    return payload, profile, call_id


def normalize_bundle_path(value: Any) -> str:
    path = str(value or "").strip()
    if not safe_rel_path(path):
        raise ValueError(f"unsafe_bundle_path:{path}")
    posix = PurePosixPath(path)
    if posix.is_absolute() or ".." in posix.parts or any(part == "" for part in posix.parts):
        raise ValueError(f"unsafe_bundle_path:{path}")
    return path


def normalize_file_content(value: Any) -> str:
    text = str(value or "").replace("\r\n", "\n")
    return text if text.endswith("\n") else text + "\n"


def normalize_files_payload(payload: dict[str, Any], unit: dict[str, Any], root: str) -> dict[str, Any]:
    entries = payload.get("files")
    if not isinstance(entries, list):
        raise ValueError("files_array_missing")
    files: dict[str, dict[str, Any]] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("file_entry_not_object")
        path = normalize_bundle_path(entry.get("path"))
        if path in files:
            raise ValueError(f"duplicate_bundle_path:{path}")
        files[path] = {
            "path": path,
            "executable": bool(entry.get("executable")),
            "content": normalize_file_content(entry.get("content")),
        }

    required = {"instruction.md", "tests/test_state.py", "tests/test.sh", "solution/solve.sh"}
    missing = sorted(required - set(files))
    if missing:
        raise ValueError(f"mandatory_files_missing:{missing}")

    partial_paths = sorted(
        path for path in files
        if path.startswith("solution/partial_solve_")
        and path.endswith(".sh")
        and len(PurePosixPath(path).parts) == 2
    )
    if not (1 <= len(partial_paths) <= 3):
        raise ValueError(f"partial_count_invalid:{len(partial_paths)}")

    instruction = files["instruction.md"]["content"].strip()
    if not instruction:
        instruction = fallback_instruction(unit, root).strip()
        files["instruction.md"]["content"] = instruction + "\n"

    files["tests/test_state.py"]["content"] = normalize_joint_test_state(files["tests/test_state.py"]["content"], root)
    files["tests/test.sh"]["content"] = normalize_joint_test_sh(files["tests/test.sh"]["content"])
    files["tests/test.sh"]["executable"] = True
    files["solution/solve.sh"]["content"] = normalize_script(files["solution/solve.sh"]["content"], root)
    files["solution/solve.sh"]["executable"] = True
    for path in partial_paths:
        files[path]["content"] = normalize_script(files[path]["content"], root)
        files[path]["executable"] = True

    return {"instruction_md": instruction, "files": [files[path] for path in sorted(files)]}


def normalize_payload(payload: dict[str, Any], unit: dict[str, Any], root: str) -> dict[str, Any]:
    if isinstance(payload.get("files"), list):
        return normalize_files_payload(payload, unit, root)
    instruction = str(payload.get("instruction_md") or "").strip()
    if not instruction:
        instruction = fallback_instruction(unit, root).strip()
    tests = payload.get("tests") if isinstance(payload.get("tests"), dict) else {}
    solution = payload.get("solution") if isinstance(payload.get("solution"), dict) else {}
    test_state = normalize_joint_test_state(str(tests.get("test_state_py") or ""), root)
    test_sh = normalize_joint_test_sh(str(tests.get("test_sh") or ""))
    solution_sh = str(solution.get("solution_sh") or "").strip()
    if not solution_sh:
        raise ValueError("solution_sh_missing")
    partials = solution.get("partials")
    if not isinstance(partials, list):
        partials = []
    return {
        "instruction_md": instruction,
        "tests": {"test_state_py": test_state, "test_sh": test_sh},
        "solution": {"solution_sh": solution_sh, "partials": partials[:3]},
    }


def write_task_bundle(ctx: RunContext, cfg: dict[str, Any], unit: dict[str, Any], payload: dict[str, Any], context: dict[str, Any], profile: str | None, call_id: str | None) -> tuple[list[str], dict[str, Any]]:
    task_id = str(unit["task_id"])
    root = task_root(cfg)
    writer = ArtifactWriter(ctx, STAGE)
    written: list[str] = []

    if isinstance(payload.get("files"), list):
        partials_written = 0
        for entry in payload["files"]:
            path = str(entry["path"])
            content = str(entry["content"])
            executable = bool(entry.get("executable"))
            written.append(writer.write_text(task_id, path, content, executable=executable))
            if path.startswith("solution/partial_solve_") and path.endswith(".sh"):
                partials_written += 1
        bundle_record = {
            "task_id": task_id,
            "generator": "facet_terminal_joint_files",
            "model_profile": profile,
            "model_call_id": call_id,
            "instruction_path": "instruction.md",
            "test_state_path": "tests/test_state.py",
            "test_sh_path": "tests/test.sh",
            "solution_path": "solution/solve.sh",
            "partial_count": partials_written,
            "canary": JOINT_CANARY,
            "context_used": {
                "instruction_ref": bool(str(context.get("instruction_ref") or "").strip()),
                "real_env_file_summary": bool(context.get("real_env_file_summary")),
                "selected_fixture_summaries": len(context.get("selected_fixture_summaries") or []),
                "generated_dockerfile": bool((context.get("generated_dockerfile") or {}).get("exists")),
            },
        }
        written.append(writer.write_json(task_id, "pipeline_artifacts/share/joint_payload.json", bundle_record))
        written.append(writer.write_json(task_id, "pipeline_artifacts/tests/test_metadata.json", {"task_id": task_id, "generator": "facet_terminal_joint_files", "test_sh_generated_by_model": True, "canary": JOINT_CANARY}))
        return written, bundle_record

    instruction = str(payload["instruction_md"]).rstrip() + "\n"
    written.append(writer.write_text(task_id, "instruction.md", instruction))

    tests = payload["tests"]
    written.append(writer.write_text(task_id, "tests/test_state.py", str(tests["test_state_py"])))
    written.append(writer.write_text(task_id, "tests/test.sh", str(tests["test_sh"]), executable=True))

    solution = payload["solution"]
    written.append(writer.write_text(task_id, "solution/solve.sh", normalize_script(str(solution["solution_sh"]), root), executable=True))
    partials_written = 0
    for index, partial in enumerate(solution.get("partials") or [], start=1):
        if not isinstance(partial, dict):
            continue
        name = str(partial.get("name") or f"partial_solve_{index}.sh")
        if not name.startswith("partial_solve_") or not name.endswith(".sh") or "/" in name:
            name = f"partial_solve_{index}.sh"
        content = normalize_script(str(partial.get("content") or ""), root)
        written.append(writer.write_text(task_id, f"solution/{name}", content, executable=True))
        partials_written += 1
    if partials_written == 0:
        fallback_partial = f"#!/bin/bash\nset -e\ncd {root}\nmkdir -p output\n"
        written.append(writer.write_text(task_id, "solution/partial_solve_missing_outputs.sh", fallback_partial, executable=True))

    bundle_record = {
        "task_id": task_id,
        "generator": "facet_terminal_joint",
        "model_profile": profile,
        "model_call_id": call_id,
        "instruction_path": "instruction.md",
        "test_state_path": "tests/test_state.py",
        "test_sh_path": "tests/test.sh",
        "solution_path": "solution/solve.sh",
        "canary": JOINT_CANARY,
        "context_used": {
            "instruction_ref": bool(str(context.get("instruction_ref") or "").strip()),
            "real_env_file_summary": bool(context.get("real_env_file_summary")),
            "selected_fixture_summaries": len(context.get("selected_fixture_summaries") or []),
            "generated_dockerfile": bool((context.get("generated_dockerfile") or {}).get("exists")),
        },
    }
    written.append(writer.write_json(task_id, "pipeline_artifacts/share/joint_payload.json", bundle_record))
    written.append(writer.write_json(task_id, "pipeline_artifacts/tests/test_metadata.json", {"task_id": task_id, "generator": "facet_terminal_joint", "test_sh_generated_by_model": True, "canary": JOINT_CANARY}))
    return written, bundle_record


def joint_one(ctx: RunContext, cfg: dict[str, Any], model_client: ModelClient | None, unit: dict[str, Any]) -> dict[str, Any]:
    task_id = str(unit["task_id"])
    root = task_root(cfg)
    try:
        mode = str(cfg.get("mode", "llm"))
        context = joint_context(ctx, cfg, unit)
        if mode == "template":
            raise ValueError("template_mode_not_supported_for_joint")
        if model_client is None:
            raise ValueError("model_client_required_for_joint")
        raw_payload, profile, call_id = payload_from_model(ctx, cfg, model_client, unit, context)
        payload = normalize_payload(raw_payload, unit, root)
        written, metadata = write_task_bundle(ctx, cfg, unit, payload, context, profile, call_id)
        report = {
            "task_id": task_id,
            "status": "joint_ready",
            "mode": mode,
            "model_profile": profile,
            "model_call_id": call_id,
            "written": written,
        }
        write_json(stage_report_dir(ctx, STAGE) / f"{task_id}.json", report)
        record_event(ctx, task_id, STAGE, "joint_ready")
        row = dict(unit)
        row["joint"] = report
        return {"status": "joint_ready", "task_id": task_id, "unit": row}
    except Exception as exc:
        report = {"task_id": task_id, "status": "joint_failed", "error": repr(exc)}
        write_json(stage_report_dir(ctx, STAGE) / f"{task_id}.json", report)
        record_event(ctx, task_id, STAGE, "joint_failed", error=repr(exc))
        return {"status": "joint_failed", "task_id": task_id, "unit": unit}


def run(ctx: RunContext, args: argparse.Namespace) -> None:
    started = utc_now()
    cfg = stage_cfg(ctx, STAGE)
    input_path = ctx.path(str(cfg.get("input_jsonl", "artifacts/facet_terminal/env_ready_units.jsonl")))
    output_path = ctx.path(str(cfg.get("output_jsonl", "artifacts/facet_terminal/joint_units.jsonl")))
    units = read_jsonl(input_path)
    if args.limit:
        units = units[: args.limit]
    model_client = ModelClient(ctx) if str(cfg.get("mode", "llm")) != "template" else None
    results = run_batched(
        "facet_terminal_joint:bundle",
        units,
        worker_count(ctx, STAGE, cfg, args.workers),
        int(cfg.get("batch_size", 8)),
        int(cfg.get("max_inflight_batches", 2)),
        lambda unit: joint_one(ctx, cfg, model_client, unit),
    )
    ready = [row["unit"] for row in results if row.get("status") == "joint_ready"]
    write_jsonl(output_path, ready)
    write_stage_report(
        ctx,
        STAGE,
        started,
        {"env_ready_units": {"path": str(input_path.relative_to(ctx.run_dir)), "hash": file_hash(input_path)}},
        {"joint_units": {"path": str(output_path.relative_to(ctx.run_dir)), "records": len(ready), "hash": file_hash(output_path)}},
        {"input_count": len(units), "joint_ready": len(ready), "joint_failed": len(results) - len(ready)},
        cfg,
    )
